# Generated by Django 3.1.7 on 2021-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20210320_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened',
            field=models.URLField(default=None, null=True, verbose_name='Shortened link'),
        ),
    ]
