# Generated by Django 3.1.7 on 2021-03-20 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_link_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='permanent',
        ),
    ]
