# Generated by Django 3.1.7 on 2021-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='header',
            field=models.CharField(default='UNNAMED', max_length=256, verbose_name='header'),
        ),
    ]
