# Generated by Django 3.1.7 on 2021-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_link_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='delete_after_watching',
            new_name='delete',
        ),
        migrations.RemoveField(
            model_name='link',
            name='header',
        ),
        migrations.RemoveField(
            model_name='link',
            name='text',
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(default=None, max_length=1024, verbose_name='link'),
            preserve_default=False,
        ),
    ]
