# Generated by Django 3.1.7 on 2021-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20210320_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='shortened',
            field=models.URLField(default=None, verbose_name='Shortened link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='uses',
            field=models.IntegerField(default=0, verbose_name='Uses count'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=1024, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='permanent',
            field=models.BooleanField(verbose_name='Is permanent'),
        ),
    ]
