# Generated by Django 3.1.7 on 2021-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20210320_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='permanent',
            field=models.BooleanField(default=False, verbose_name='Is permanent'),
        ),
        migrations.AlterField(
            model_name='link',
            name='uses',
            field=models.IntegerField(default=0, verbose_name='Uses count'),
        ),
    ]
