# Generated by Django 3.1.7 on 2021-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20210320_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='delete',
        ),
        migrations.AddField(
            model_name='link',
            name='permanent',
            field=models.BooleanField(default=None, verbose_name='permanent'),
            preserve_default=False,
        ),
    ]
