# Generated by Django 3.1.7 on 2021-03-20 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20210320_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
